apiVersion: v1
kind: Service
metadata:
    name: david-svc
    labels:
        app: david
spec:
    type: NodePort
    selector:
        app: david
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30080
